import { pgTable, text, timestamp, boolean, uniqueIndex, index } from 'drizzle-orm/pg-core'

/**
 * `examples` — starter table to demonstrate the Drizzle + PostgreSQL pattern.
 *
 * Replace or extend this with your own domain tables.
 * Nested objects should be stored as JSON text columns (serialize before
 * insert, parse after select) — see KevinPulse's fuel_price_entries for
 * a real-world example.
 */
export const examples = pgTable('examples', {
  /** UUID string — generate with crypto.randomUUID() */
  id: text('id').primaryKey(),

  /** Human-readable name */
  name: text('name').notNull(),

  /** Optional description */
  description: text('description'),

  /** Timestamp — set on insert, never updated */
  createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
})

export type ExampleRow = typeof examples.$inferSelect
export type NewExampleRow = typeof examples.$inferInsert

/**
 * `projects` — a demo table for RBAC.
 */
export const projects = pgTable('projects', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
})

export type ProjectRow = typeof projects.$inferSelect
export type NewProjectRow = typeof projects.$inferInsert

// ---------------------------------------------------------------------------
// better-auth tables — generated by @better-auth/cli, adapted for this repo
// ---------------------------------------------------------------------------

/** Core user record. `role` / `banned` columns added by the admin plugin. */
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).notNull(),
  // admin plugin columns
  role: text('role'),
  banned: boolean('banned'),
  banReason: text('ban_reason'),
  banExpires: timestamp('ban_expires', { mode: 'date' }),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at', { mode: 'date' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', { mode: 'date' }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { mode: 'date' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
  updatedAt: timestamp('updated_at', { mode: 'date' }).notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { mode: 'date' }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }),
  updatedAt: timestamp('updated_at', { mode: 'date' }),
})

// ---------------------------------------------------------------------------
// Resource-scoped grants — your custom per-resource RBAC layer
// ---------------------------------------------------------------------------

/**
 * `resource_roles` — ties a user to a role on a specific resource instance.
 *
 * Example row:
 *   userId = "user-uuid"
 *   resourceType = "project"
 *   resourceId = "project-uuid"
 *   role = "editor"
 *
 * Global admins bypass this table entirely (see src/modules/rbac/can.ts).
 */
export const resourceRoles = pgTable(
  'resource_roles',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** e.g. 'project', 'report', 'team' */
    resourceType: text('resource_type').notNull(),
    /** The PK of the specific resource row */
    resourceId: text('resource_id').notNull(),
    /** e.g. 'editor', 'viewer' — see src/modules/rbac/resourcePermissions.ts */
    role: text('role').notNull(),
    createdAt: timestamp('created_at', { mode: 'date' }).notNull(),
  },
  (t) => [
    uniqueIndex('resource_roles_uniq').on(t.userId, t.resourceType, t.resourceId),
    index('resource_roles_lookup').on(t.resourceType, t.resourceId),
  ],
)

export type ResourceRoleRow = typeof resourceRoles.$inferSelect
export type NewResourceRoleRow = typeof resourceRoles.$inferInsert
