import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core'

/**
 * `examples` — starter table to demonstrate the Drizzle + SQLite pattern.
 *
 * Replace or extend this with your own domain tables.
 * Nested objects should be stored as JSON text columns (serialize before
 * insert, parse after select) — see KevinPulse's fuel_price_entries for
 * a real-world example.
 */
export const examples = sqliteTable('examples', {
  /** UUID string — generate with crypto.randomUUID() */
  id: text('id').primaryKey(),

  /** Human-readable name */
  name: text('name').notNull(),

  /** Optional description */
  description: text('description'),

  /** Unix timestamp (ms) — set on insert, never updated */
  createdAt: integer('created_at').notNull(),
})

export type ExampleRow = typeof examples.$inferSelect
export type NewExampleRow = typeof examples.$inferInsert

/**
 * `projects` — a demo table for RBAC.
 */
export const projects = sqliteTable('projects', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  createdAt: integer('created_at').notNull(),
})

export type ProjectRow = typeof projects.$inferSelect
export type NewProjectRow = typeof projects.$inferInsert

// ---------------------------------------------------------------------------
// better-auth tables — generated by @better-auth/cli, adapted for this repo
// ---------------------------------------------------------------------------

/** Core user record. `role` / `banned` columns added by the admin plugin. */
export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
  image: text('image'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  // admin plugin columns
  role: text('role'),
  banned: integer('banned', { mode: 'boolean' }),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires', { mode: 'timestamp' }),
})

export const session = sqliteTable('session', {
  id: text('id').primaryKey(),
  expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

export const account = sqliteTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp' }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }),
  updatedAt: integer('updated_at', { mode: 'timestamp' }),
})

// ---------------------------------------------------------------------------
// Resource-scoped grants — your custom per-resource RBAC layer
// ---------------------------------------------------------------------------

/**
 * `resource_roles` — ties a user to a role on a specific resource instance.
 *
 * Example row:
 *   userId = "user-uuid"
 *   resourceType = "project"
 *   resourceId = "project-uuid"
 *   role = "editor"
 *
 * Global admins bypass this table entirely (see src/modules/rbac/can.ts).
 */
export const resourceRoles = sqliteTable(
  'resource_roles',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** e.g. 'project', 'report', 'team' */
    resourceType: text('resource_type').notNull(),
    /** The PK of the specific resource row */
    resourceId: text('resource_id').notNull(),
    /** e.g. 'editor', 'viewer' — see src/modules/rbac/resourcePermissions.ts */
    role: text('role').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [
    uniqueIndex('resource_roles_uniq').on(t.userId, t.resourceType, t.resourceId),
    index('resource_roles_lookup').on(t.resourceType, t.resourceId),
  ],
)

export type ResourceRoleRow = typeof resourceRoles.$inferSelect
export type NewResourceRoleRow = typeof resourceRoles.$inferInsert
